version: '3'

tasks:
  router:
    cmds:
      - task: update-local
      - task: update-remote

  update-local:
    internal: true
    cmds:
      - rsync -ahAEO .gitignore .rules .sops.yaml containers README.md apply-router.sh secrets.sops.env Taskfile.yaml router:/config/
      - rsync -ahAEO --delete router-parts scripts router:/config/
      - ssh router -t "sudo chown -R router:vyattacfg /config && sudo chown -R dhcpd:vyattacfg  /config/dhcpd.leases*"
      - ssh router -t "cd /config && ./apply-router.sh"

  update-remote:
    internal: true
    cmds:
      - echo
