version: '3'

tasks:
  router:
    cmds:
      - task: update-router
      - task: apply-router

  update-router:
    internal: true
    cmds:
      - ssh router -t "sudo chown -R router:vyattacfg /config && sudo chown -R _kea:_kea /config/dhcp"
      - ssh router -t "cd /config && git fetch --all && git reset --hard HEAD && git pull"

  apply-router:
    internal: true
    cmds:
      - ssh router -t "cd /config && ./apply-router.sh"

  dns-update:
    cmds:
      - rsync -avz ./containers/bind router:/config/containers/
      - ssh router -t "/opt/vyatta/bin/vyatta-op-cmd-wrapper restart container bind"