---
ports:
  dns: 53

upstream:
  default:
    - tcp-tls:1.1.1.1:853
    - tcp-tls:1.0.0.1:853
    - 1.1.1.1
    - 1.0.0.1

clientLookup:
 upstream: 10.40.0.5

startVerifyUpstream: true
connectIPVersion: v4

blocking:
  blackLists:
    ads:
      - http://sysctl.org/cameleon/hosts
      - https://big.oisd.nl/hosts
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
  clientGroupsBlock:
    default:
      - ads
  blockType: zeroIp

prometheus:
  enable: true
  path: /metrics

minTlsServeVersion: 1.3
bootstrapDns:
  - tcp+udp:1.1.1.1
  - https://1.1.1.1/dns-query

filtering:
  queryTypes:
    - AAAA

log:
  level: warn
