#!/bin/vbash
# shellcheck shell=bash
# shellcheck source=/dev/null

set firewall zone TRUSTED default-action 'drop'
set firewall zone TRUSTED from GUEST firewall name 'GUEST-TRUSTED'
set firewall zone TRUSTED from SECURITY firewall name 'SECURITY-TRUSTED'
set firewall zone TRUSTED from SERVERS firewall name 'SERVERS-TRUSTED'
set firewall zone TRUSTED from IOT firewall name 'IOT-TRUSTED'
set firewall zone TRUSTED from MGMT firewall name 'MGMT-TRUSTED'
set firewall zone TRUSTED from CONTAINERS firewall name 'CONTAINERS-TRUSTED'
set firewall zone TRUSTED from LOCAL firewall name 'LOCAL-TRUSTED'
set firewall zone TRUSTED from WAN firewall name 'WAN-TRUSTED'
set firewall zone TRUSTED interface 'eth0.10'
set firewall zone TRUSTED interface 'wg01'

set firewall zone GUEST default-action 'drop'
set firewall zone GUEST from TRUSTED firewall name 'TRUSTED-GUEST'
set firewall zone GUEST from SECURITY firewall name 'SECURITY-GUEST'
set firewall zone GUEST from SERVERS firewall name 'SERVERS-GUEST'
set firewall zone GUEST from IOT firewall name 'IOT-GUEST'
set firewall zone GUEST from MGMT firewall name 'MGMT-GUEST'
set firewall zone GUEST from CONTAINERS firewall name 'CONTAINERS-GUEST'
set firewall zone GUEST from LOCAL firewall name 'LOCAL-GUEST'
set firewall zone GUEST from WAN firewall name 'WAN-GUEST'
set firewall zone GUEST interface 'eth0.20'

set firewall zone SECURITY default-action 'drop'
set firewall zone SECURITY from TRUSTED firewall name 'TRUSTED-SECURITY'
set firewall zone SECURITY from GUEST firewall name 'GUEST-SECURITY'
set firewall zone SECURITY from SERVERS firewall name 'SERVERS-SECURITY'
set firewall zone SECURITY from IOT firewall name 'IOT-SECURITY'
set firewall zone SECURITY from MGMT firewall name 'MGMT-SECURITY'
set firewall zone SECURITY from CONTAINERS firewall name 'CONTAINERS-SECURITY'
set firewall zone SECURITY from LOCAL firewall name 'LOCAL-SECURITY'
set firewall zone SECURITY from WAN firewall name 'WAN-SECURITY'
set firewall zone SECURITY interface 'eth0.30'

set firewall zone SERVERS default-action 'drop'
set firewall zone SERVERS from TRUSTED firewall name 'TRUSTED-SERVERS'
set firewall zone SERVERS from GUEST firewall name 'GUEST-SERVERS'
set firewall zone SERVERS from SECURITY firewall name 'SECURITY-SERVERS'
set firewall zone SERVERS from IOT firewall name 'IOT-SERVERS'
set firewall zone SERVERS from MGMT firewall name 'MGMT-SERVERS'
set firewall zone SERVERS from CONTAINERS firewall name 'CONTAINERS-SERVERS'
set firewall zone SERVERS from LOCAL firewall name 'LOCAL-SERVERS'
set firewall zone SERVERS from WAN firewall name 'WAN-SERVERS'
set firewall zone SERVERS interface 'eth0.40'

set firewall zone IOT default-action 'drop'
set firewall zone IOT from TRUSTED firewall name 'TRUSTED-IOT'
set firewall zone IOT from GUEST firewall name 'GUEST-IOT'
set firewall zone IOT from SECURITY firewall name 'SECURITY-IOT'
set firewall zone IOT from SERVERS firewall name 'SERVERS-IOT'
set firewall zone IOT from MGMT firewall name 'MGMT-IOT'
set firewall zone IOT from CONTAINERS firewall name 'CONTAINERS-IOT'
set firewall zone IOT from LOCAL firewall name 'LOCAL-IOT'
set firewall zone IOT from WAN firewall name 'WAN-IOT'
set firewall zone IOT interface 'eth0.50'

set firewall zone MGMT default-action 'drop'
set firewall zone MGMT from TRUSTED firewall name 'TRUSTED-MGMT'
set firewall zone MGMT from GUEST firewall name 'GUEST-MGMT'
set firewall zone MGMT from SECURITY firewall name 'SECURITY-MGMT'
set firewall zone MGMT from SERVERS firewall name 'SERVERS-MGMT'
set firewall zone MGMT from IOT firewall name 'IOT-MGMT'
set firewall zone MGMT from CONTAINERS firewall name 'CONTAINERS-MGMT'
set firewall zone MGMT from LOCAL firewall name 'LOCAL-MGMT'
set firewall zone MGMT from WAN firewall name 'WAN-MGMT'
set firewall zone MGMT interface 'eth0.70'

set firewall zone CONTAINERS default-action 'drop'
set firewall zone CONTAINERS from TRUSTED firewall name 'TRUSTED-CONTAINERS'
set firewall zone CONTAINERS from GUEST firewall name 'GUEST-CONTAINERS'
set firewall zone CONTAINERS from SECURITY firewall name 'SECURITY-CONTAINERS'
set firewall zone CONTAINERS from SERVERS firewall name 'SERVERS-CONTAINERS'
set firewall zone CONTAINERS from IOT firewall name 'IOT-CONTAINERS'
set firewall zone CONTAINERS from MGMT firewall name 'MGMT-CONTAINERS'
set firewall zone CONTAINERS from LOCAL firewall name 'LOCAL-CONTAINERS'
set firewall zone CONTAINERS from WAN firewall name 'WAN-CONTAINERS'
set firewall zone CONTAINERS interface 'pod-containers'

set firewall zone LOCAL default-action 'drop'
set firewall zone LOCAL description 'Local Router Zone'
set firewall zone LOCAL from TRUSTED firewall name 'TRUSTED-LOCAL'
set firewall zone LOCAL from GUEST firewall name 'GUEST-LOCAL'
set firewall zone LOCAL from SECURITY firewall name 'SECURITY-LOCAL'
set firewall zone LOCAL from SERVERS firewall name 'SERVERS-LOCAL'
set firewall zone LOCAL from IOT firewall name 'IOT-LOCAL'
set firewall zone LOCAL from MGMT firewall name 'MGMT-LOCAL'
set firewall zone LOCAL from CONTAINERS firewall name 'CONTAINERS-LOCAL'
set firewall zone LOCAL from WAN firewall name 'WAN-LOCAL'
set firewall zone LOCAL local-zone

set firewall zone WAN default-action 'drop'
set firewall zone WAN from TRUSTED firewall name 'TRUSTED-WAN'
set firewall zone WAN from GUEST firewall name 'GUEST-WAN'
set firewall zone WAN from SECURITY firewall name 'SECURITY-WAN'
set firewall zone WAN from SERVERS firewall name 'SERVERS-WAN'
set firewall zone WAN from IOT firewall name 'IOT-WAN'
set firewall zone WAN from MGMT firewall name 'MGMT-WAN'
set firewall zone WAN from CONTAINERS firewall name 'CONTAINERS-WAN'
set firewall zone WAN from LOCAL firewall name 'LOCAL-WAN'
set firewall zone WAN interface 'eth2'
