---
name: Schedule - Renovate

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json5"
      - ".github/workflows/schedule-renovate.yaml"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.BAYMAX_APP_ID }}
          private_key: ${{ secrets.BAYMAX_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.1.1
        with:
          configurationFile: .github/renovate.json5
          token: '${{ steps.get_token.outputs.token }}'
